import { ProjectDocument } from "@/types";

/**
 * 書類マスタアイテムの型定義
 * ProjectDocumentから id, projectId, createdAt, updatedAt, fileUrl, storagePath, masterDocumentId を除外 + idを追加
 */
export interface DocumentMasterItem {
  id: string;                          // マスタ書類ID（固定の文字列ID）
  name: string;                        // 書類名（必須）
  description?: string;                // 書類の説明
  category: 'personal' | 'employer' | 'office' | 'government' | 'other';
  source: 'office' | 'applicant' | 'employer' | 'government' | 'guarantor' | 'other';
  assignedTo: 'office' | 'applicant';
  status: 'not_started' | 'in_progress' | 'waiting' | 'collected' | 'verified' | 'completed';
  isRequiredOriginal: boolean;
}

/**
 * 書類名からIDを生成する関数
 */
function generateDocumentId(name: string): string {
  // 書類名をベースにユニークなIDを生成
  // 日本語名からローマ字読み風のIDを生成（簡易版）
  const idMap: Record<string, string> = {
    "在留資格変更許可申請書": "master-doc-visa-change-application",
    "パスポートの写し": "master-doc-passport",
    "在留カードの写し": "master-doc-residence-card",
    "写真": "master-doc-photo",
    "在留資格変更許可申請書の添付書類": "master-doc-visa-change-attachment",
    "履歴書": "master-doc-resume",
    "卒業証明書": "master-doc-graduation-certificate",
    "成績証明書": "master-doc-transcript",
    "雇用契約書の写し": "master-doc-employment-contract",
    "給与明細書": "master-doc-pay-slip",
    "源泉徴収票": "master-doc-tax-withholding",
    "会社の登記事項証明書": "master-doc-company-registry",
    "会社案内": "master-doc-company-brochure",
    "従業員数・外国人従業員数の証明書": "master-doc-employee-count",
    "事業内容説明書": "master-doc-business-description",
    "雇用理由書": "master-doc-employment-reason",
    "申請人の職務内容説明書": "master-doc-job-description",
    "申請人の経歴書": "master-doc-career-history",
    "住民票の写し": "master-doc-residence-certificate",
    "納税証明書": "master-doc-tax-certificate",
    "健康保険証の写し": "master-doc-health-insurance",
    "年金記録の確認応答書": "master-doc-pension-record",
    "申請人の職務に関する証明書": "master-doc-job-certificate",
    "申請人の学歴に関する証明書": "master-doc-education-certificate",
    "申請人の資格に関する証明書": "master-doc-qualification-certificate",
    "申請人の語学能力に関する証明書": "master-doc-language-certificate",
    "申請人の職務に関する実務経験証明書": "master-doc-work-experience",
    "申請人の職務に関する専門性証明書": "master-doc-expertise-certificate",
    "申請人の職務に関する報酬証明書": "master-doc-compensation-certificate",
    "永住許可申請書": "master-doc-permanent-residence-application",
    "課税証明書": "master-doc-tax-liability-certificate",
    "身元保証書": "master-doc-guarantor-letter",
    "身元保証人の住民票の写し": "master-doc-guarantor-residence",
    "身元保証人の在職証明書": "master-doc-guarantor-employment",
    "身元保証人の身分証明書の写し": "master-doc-guarantor-id",
    "申請理由書": "master-doc-application-reason",
    "素行が良好であることの証明書": "master-doc-conduct-certificate",
    "独立の生計を営むに足りる資産又は技能を有することの証明書": "master-doc-means-certificate",
    "預金通帳の写し": "master-doc-bankbook",
    "不動産登記簿謄本": "master-doc-real-estate-registry",
    "配偶者の在留カードの写し": "master-doc-spouse-residence-card",
    "配偶者の住民票の写し": "master-doc-spouse-residence",
    "配偶者の納税証明書": "master-doc-spouse-tax-certificate",
    "子供の在留カードの写し": "master-doc-child-residence-card",
    "子供の住民票の写し": "master-doc-child-residence",
    "健康診断書": "master-doc-health-check",
    "その他参考資料": "master-doc-other-reference",
  };
  
  return idMap[name] || `master-doc-${name.replace(/\s+/g, '-').toLowerCase()}`;
}

/**
 * 必要書類マスタリスト
 * 既存のテンプレートから全書類を抽出し、重複を排除したもの
 */
export const documentMasterList: DocumentMasterItem[] = [
  {
    id: generateDocumentId("在留資格変更許可申請書"),
    name: "在留資格変更許可申請書",
    description: "1通",
    category: "office",
    source: "office",
    assignedTo: "office",
    status: "not_started",
    isRequiredOriginal: false,
  },
  {
    id: generateDocumentId("パスポートの写し"),
    name: "パスポートの写し",
    description: "顔写真のあるページ",
    category: "personal",
    source: "applicant",
    assignedTo: "applicant",
    status: "not_started",
    isRequiredOriginal: true,
  },
  {
    id: generateDocumentId("在留カードの写し"),
    name: "在留カードの写し",
    description: "表裏両面",
    category: "personal",
    source: "applicant",
    assignedTo: "applicant",
    status: "not_started",
    isRequiredOriginal: true,
  },
  {
    id: generateDocumentId("写真"),
    name: "写真",
    description: "縦4cm×横3cm、3ヶ月以内に撮影",
    category: "personal",
    source: "applicant",
    assignedTo: "applicant",
    status: "not_started",
    isRequiredOriginal: false,
  },
  {
    id: generateDocumentId("在留資格変更許可申請書の添付書類"),
    name: "在留資格変更許可申請書の添付書類",
    description: "申請理由書",
    category: "office",
    source: "office",
    assignedTo: "office",
    status: "not_started",
    isRequiredOriginal: false,
  },
  {
    id: generateDocumentId("履歴書"),
    name: "履歴書",
    description: "職歴を詳しく記載",
    category: "personal",
    source: "applicant",
    assignedTo: "applicant",
    status: "not_started",
    isRequiredOriginal: false,
  },
  {
    id: generateDocumentId("卒業証明書"),
    name: "卒業証明書",
    description: "最終学歴のもの",
    category: "personal",
    source: "applicant",
    assignedTo: "applicant",
    status: "not_started",
    isRequiredOriginal: true,
  },
  {
    id: generateDocumentId("成績証明書"),
    name: "成績証明書",
    description: "最終学歴のもの",
    category: "personal",
    source: "applicant",
    assignedTo: "applicant",
    status: "not_started",
    isRequiredOriginal: true,
  },
  {
    id: generateDocumentId("雇用契約書の写し"),
    name: "雇用契約書の写し",
    description: "または採用内定通知書",
    category: "employer",
    source: "employer",
    assignedTo: "applicant",
    status: "not_started",
    isRequiredOriginal: false,
  },
  {
    id: generateDocumentId("給与明細書"),
    name: "給与明細書",
    description: "直近3ヶ月分",
    category: "employer",
    source: "employer",
    assignedTo: "applicant",
    status: "not_started",
    isRequiredOriginal: false,
  },
  {
    id: generateDocumentId("源泉徴収票"),
    name: "源泉徴収票",
    description: "直近1年分",
    category: "employer",
    source: "employer",
    assignedTo: "applicant",
    status: "not_started",
    isRequiredOriginal: true,
  },
  {
    id: generateDocumentId("会社の登記事項証明書"),
    name: "会社の登記事項証明書",
    description: "3ヶ月以内発行のもの",
    category: "employer",
    source: "employer",
    assignedTo: "applicant",
    status: "not_started",
    isRequiredOriginal: true,
  },
  {
    id: generateDocumentId("会社案内"),
    name: "会社案内",
    description: "事業内容が分かるもの",
    category: "employer",
    source: "employer",
    assignedTo: "applicant",
    status: "not_started",
    isRequiredOriginal: false,
  },
  {
    id: generateDocumentId("従業員数・外国人従業員数の証明書"),
    name: "従業員数・外国人従業員数の証明書",
    description: "会社が作成",
    category: "employer",
    source: "employer",
    assignedTo: "applicant",
    status: "not_started",
    isRequiredOriginal: false,
  },
  {
    id: generateDocumentId("事業内容説明書"),
    name: "事業内容説明書",
    description: "会社が作成",
    category: "employer",
    source: "employer",
    assignedTo: "applicant",
    status: "not_started",
    isRequiredOriginal: false,
  },
  {
    id: generateDocumentId("雇用理由書"),
    name: "雇用理由書",
    description: "会社が作成",
    category: "employer",
    source: "employer",
    assignedTo: "applicant",
    status: "not_started",
    isRequiredOriginal: false,
  },
  {
    id: generateDocumentId("申請人の職務内容説明書"),
    name: "申請人の職務内容説明書",
    description: "会社が作成",
    category: "employer",
    source: "employer",
    assignedTo: "applicant",
    status: "not_started",
    isRequiredOriginal: false,
  },
  {
    id: generateDocumentId("申請人の経歴書"),
    name: "申請人の経歴書",
    description: "職務経歴を詳しく記載",
    category: "personal",
    source: "applicant",
    assignedTo: "applicant",
    status: "not_started",
    isRequiredOriginal: false,
  },
  {
    id: generateDocumentId("住民票の写し"),
    name: "住民票の写し",
    description: "3ヶ月以内発行のもの",
    category: "government",
    source: "applicant",
    assignedTo: "applicant",
    status: "not_started",
    isRequiredOriginal: true,
  },
  {
    id: generateDocumentId("納税証明書"),
    name: "納税証明書",
    description: "直近1年分",
    category: "government",
    source: "government",
    assignedTo: "applicant",
    status: "not_started",
    isRequiredOriginal: true,
  },
  {
    id: generateDocumentId("健康保険証の写し"),
    name: "健康保険証の写し",
    description: "表裏両面",
    category: "personal",
    source: "applicant",
    assignedTo: "applicant",
    status: "not_started",
    isRequiredOriginal: false,
  },
  {
    id: generateDocumentId("年金記録の確認応答書"),
    name: "年金記録の確認応答書",
    description: "直近1年分",
    category: "government",
    source: "government",
    assignedTo: "applicant",
    status: "not_started",
    isRequiredOriginal: true,
  },
  {
    id: generateDocumentId("申請人の職務に関する証明書"),
    name: "申請人の職務に関する証明書",
    description: "会社が作成",
    category: "employer",
    source: "employer",
    assignedTo: "applicant",
    status: "not_started",
    isRequiredOriginal: false,
  },
  {
    id: generateDocumentId("申請人の学歴に関する証明書"),
    name: "申請人の学歴に関する証明書",
    description: "最終学歴のもの",
    category: "personal",
    source: "applicant",
    assignedTo: "applicant",
    status: "not_started",
    isRequiredOriginal: true,
  },
  {
    id: generateDocumentId("申請人の資格に関する証明書"),
    name: "申請人の資格に関する証明書",
    description: "関連資格がある場合",
    category: "personal",
    source: "applicant",
    assignedTo: "applicant",
    status: "not_started",
    isRequiredOriginal: true,
  },
  {
    id: generateDocumentId("申請人の語学能力に関する証明書"),
    name: "申請人の語学能力に関する証明書",
    description: "TOEIC、TOEFL等",
    category: "personal",
    source: "applicant",
    assignedTo: "applicant",
    status: "not_started",
    isRequiredOriginal: false,
  },
  {
    id: generateDocumentId("申請人の職務に関する実務経験証明書"),
    name: "申請人の職務に関する実務経験証明書",
    description: "会社が作成",
    category: "employer",
    source: "employer",
    assignedTo: "applicant",
    status: "not_started",
    isRequiredOriginal: false,
  },
  {
    id: generateDocumentId("申請人の職務に関する専門性証明書"),
    name: "申請人の職務に関する専門性証明書",
    description: "会社が作成",
    category: "employer",
    source: "employer",
    assignedTo: "applicant",
    status: "not_started",
    isRequiredOriginal: false,
  },
  {
    id: generateDocumentId("申請人の職務に関する報酬証明書"),
    name: "申請人の職務に関する報酬証明書",
    description: "会社が作成",
    category: "employer",
    source: "employer",
    assignedTo: "applicant",
    status: "not_started",
    isRequiredOriginal: false,
  },
  {
    id: generateDocumentId("永住許可申請書"),
    name: "永住許可申請書",
    description: "1通",
    category: "office",
    source: "office",
    assignedTo: "office",
    status: "not_started",
    isRequiredOriginal: false,
  },
  {
    id: generateDocumentId("課税証明書"),
    name: "課税証明書",
    description: "直近5年分",
    category: "government",
    source: "government",
    assignedTo: "applicant",
    status: "not_started",
    isRequiredOriginal: true,
  },
  {
    id: generateDocumentId("身元保証書"),
    name: "身元保証書",
    description: "身元保証人が作成",
    category: "other",
    source: "guarantor",
    assignedTo: "applicant",
    status: "not_started",
    isRequiredOriginal: false,
  },
  {
    id: generateDocumentId("身元保証人の住民票の写し"),
    name: "身元保証人の住民票の写し",
    description: "3ヶ月以内発行のもの",
    category: "other",
    source: "guarantor",
    assignedTo: "applicant",
    status: "not_started",
    isRequiredOriginal: true,
  },
  {
    id: generateDocumentId("身元保証人の在職証明書"),
    name: "身元保証人の在職証明書",
    description: "または納税証明書",
    category: "other",
    source: "guarantor",
    assignedTo: "applicant",
    status: "not_started",
    isRequiredOriginal: true,
  },
  {
    id: generateDocumentId("身元保証人の身分証明書の写し"),
    name: "身元保証人の身分証明書の写し",
    description: "運転免許証等",
    category: "other",
    source: "guarantor",
    assignedTo: "applicant",
    status: "not_started",
    isRequiredOriginal: true,
  },
  {
    id: generateDocumentId("申請理由書"),
    name: "申請理由書",
    description: "永住許可を希望する理由",
    category: "office",
    source: "office",
    assignedTo: "office",
    status: "not_started",
    isRequiredOriginal: false,
  },
  {
    id: generateDocumentId("素行が良好であることの証明書"),
    name: "素行が良好であることの証明書",
    description: "犯罪歴がないことの証明",
    category: "government",
    source: "government",
    assignedTo: "applicant",
    status: "not_started",
    isRequiredOriginal: true,
  },
  {
    id: generateDocumentId("独立の生計を営むに足りる資産又は技能を有することの証明書"),
    name: "独立の生計を営むに足りる資産又は技能を有することの証明書",
    description: "資産証明書等",
    category: "personal",
    source: "applicant",
    assignedTo: "applicant",
    status: "not_started",
    isRequiredOriginal: true,
  },
  {
    id: generateDocumentId("預金通帳の写し"),
    name: "預金通帳の写し",
    description: "直近1年分",
    category: "personal",
    source: "applicant",
    assignedTo: "applicant",
    status: "not_started",
    isRequiredOriginal: false,
  },
  {
    id: generateDocumentId("不動産登記簿謄本"),
    name: "不動産登記簿謄本",
    description: "不動産を所有している場合",
    category: "personal",
    source: "applicant",
    assignedTo: "applicant",
    status: "not_started",
    isRequiredOriginal: true,
  },
  {
    id: generateDocumentId("配偶者の在留カードの写し"),
    name: "配偶者の在留カードの写し",
    description: "配偶者がいる場合",
    category: "personal",
    source: "applicant",
    assignedTo: "applicant",
    status: "not_started",
    isRequiredOriginal: true,
  },
  {
    id: generateDocumentId("配偶者の住民票の写し"),
    name: "配偶者の住民票の写し",
    description: "配偶者がいる場合",
    category: "government",
    source: "applicant",
    assignedTo: "applicant",
    status: "not_started",
    isRequiredOriginal: true,
  },
  {
    id: generateDocumentId("配偶者の納税証明書"),
    name: "配偶者の納税証明書",
    description: "配偶者がいる場合、直近5年分",
    category: "government",
    source: "government",
    assignedTo: "applicant",
    status: "not_started",
    isRequiredOriginal: true,
  },
  {
    id: generateDocumentId("子供の在留カードの写し"),
    name: "子供の在留カードの写し",
    description: "子供がいる場合",
    category: "personal",
    source: "applicant",
    assignedTo: "applicant",
    status: "not_started",
    isRequiredOriginal: true,
  },
  {
    id: generateDocumentId("子供の住民票の写し"),
    name: "子供の住民票の写し",
    description: "子供がいる場合",
    category: "government",
    source: "applicant",
    assignedTo: "applicant",
    status: "not_started",
    isRequiredOriginal: true,
  },
  {
    id: generateDocumentId("健康診断書"),
    name: "健康診断書",
    description: "3ヶ月以内発行のもの",
    category: "personal",
    source: "applicant",
    assignedTo: "applicant",
    status: "not_started",
    isRequiredOriginal: true,
  },
  {
    id: generateDocumentId("その他参考資料"),
    name: "その他参考資料",
    description: "必要に応じて追加",
    category: "other",
    source: "other",
    assignedTo: "applicant",
    status: "not_started",
    isRequiredOriginal: false,
  },
];

