import { Project, ProjectDocument } from "@/types";

// モックデータ用の現在日時
const now = new Date();
const yesterday = new Date(now);
yesterday.setDate(yesterday.getDate() - 1);
const lastWeek = new Date(now);
lastWeek.setDate(lastWeek.getDate() - 7);
const nextMonth = new Date(now);
nextMonth.setMonth(nextMonth.getMonth() + 1);
const nextWeek = new Date(now);
nextWeek.setDate(nextWeek.getDate() + 7);

// 期限切れ間近（7日以内）
const deadlineNear1 = new Date(now);
deadlineNear1.setDate(now.getDate() + 3);
const deadlineNear2 = new Date(now);
deadlineNear2.setDate(now.getDate() + 5);
const deadlineNear3 = new Date(now);
deadlineNear3.setDate(now.getDate() + 6);

// 期限切れ
const expired1 = new Date(now);
expired1.setDate(now.getDate() - 5);
const expired2 = new Date(now);
expired2.setDate(now.getDate() - 15);
const expired3DaysAgo = new Date(now);
expired3DaysAgo.setDate(now.getDate() - 3);

// 通常の期限
const normalDeadline1 = new Date(now);
normalDeadline1.setDate(now.getDate() + 30);
const normalDeadline2 = new Date(now);
normalDeadline2.setDate(now.getDate() + 60);
const normalDeadline3 = new Date(now);
normalDeadline3.setDate(now.getDate() + 90);

/**
 * 旧ステータス文字列を新しいステータス型に変換
 */
function convertStatus(oldStatus: string): 'active' | 'pending' | 'completed' {
  if (oldStatus === '完了') {
    return 'completed';
  }
  if (oldStatus === '審査中') {
    return 'active';
  }
  // "申請準備中", "書類収集中", "準備中" などは pending
  return 'pending';
}

/**
 * プロジェクトのモックデータ
 */
export const mockProjects: Project[] = [
  {
    id: "mock-project-1",
    title: "技術・人文知識・国際業務の申請",
    name: "田中太郎",
    nameEnglish: "Taro Tanaka",
    nationality: "日本",
    visaType: "技術・人文知識・国際業務",
    currentVisaType: "技術・人文知識・国際業務",
    expiryDate: nextMonth,
    status: convertStatus("申請準備中"),
    createdAt: lastWeek,
    updatedAt: yesterday,
  },
  {
    id: "mock-project-2",
    title: "経営・管理ビザの申請",
    name: "Smith John",
    nameEnglish: "John Smith",
    nationality: "アメリカ",
    visaType: "経営・管理",
    currentVisaType: "技術・人文知識・国際業務",
    expiryDate: nextWeek,
    status: convertStatus("審査中"),
    createdAt: new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000),
    updatedAt: yesterday,
  },
  {
    id: "mock-project-3",
    title: "永住許可の申請",
    name: "佐藤花子",
    nameEnglish: "Hanako Sato",
    nationality: "日本",
    visaType: "永住許可",
    currentVisaType: "技術・人文知識・国際業務",
    expiryDate: null,
    status: convertStatus("準備中"),
    createdAt: new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000),
  },
  {
    id: "mock-project-4",
    title: "留学ビザの申請",
    name: "李小明",
    nameEnglish: "Xiaoming Li",
    nationality: "中国",
    visaType: "留学",
    currentVisaType: "短期滞在",
    expiryDate: nextWeek,
    status: convertStatus("書類収集中"),
    createdAt: new Date(now.getTime() - 10 * 24 * 60 * 60 * 1000),
    updatedAt: yesterday,
  },
  {
    id: "mock-project-5",
    title: "高度専門職ビザの申請",
    name: "Park Min-ji",
    nameEnglish: "Min-ji Park",
    nationality: "韓国",
    visaType: "高度専門職",
    currentVisaType: "技術・人文知識・国際業務",
    expiryDate: nextMonth,
    status: convertStatus("審査中"),
    createdAt: new Date(now.getTime() - 14 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000),
  },
  {
    id: "mock-project-6",
    title: "家族滞在ビザの申請",
    name: "山田次郎",
    nameEnglish: "Jiro Yamada",
    nationality: "日本",
    visaType: "家族滞在",
    currentVisaType: "短期滞在",
    expiryDate: null,
    status: convertStatus("完了"),
    createdAt: new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(now.getTime() - 1 * 24 * 60 * 60 * 1000),
  },
  {
    id: "mock-project-7",
    title: "技能実習ビザの申請",
    name: "Nguyen Van A",
    nameEnglish: "Van A Nguyen",
    nationality: "ベトナム",
    visaType: "技能実習",
    currentVisaType: "短期滞在",
    expiryDate: nextMonth,
    status: convertStatus("準備中"),
    createdAt: new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000),
  },
  {
    id: "mock-project-8",
    title: "定住者ビザの申請",
    name: "Garcia Maria",
    nameEnglish: "Maria Garcia",
    nationality: "フィリピン",
    visaType: "定住者",
    currentVisaType: "家族滞在",
    expiryDate: deadlineNear1, // 期限切れ間近
    status: convertStatus("審査中"),
    createdAt: new Date(now.getTime() - 8 * 24 * 60 * 60 * 1000),
    updatedAt: yesterday,
  },
  {
    id: "mock-project-9",
    title: "技術・人文知識・国際業務の申請",
    name: "Patel Raj",
    nameEnglish: "Raj Patel",
    nationality: "インド",
    visaType: "技術・人文知識・国際業務",
    currentVisaType: "留学",
    expiryDate: deadlineNear2, // 期限切れ間近
    status: convertStatus("申請準備中"),
    createdAt: new Date(now.getTime() - 12 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(now.getTime() - 1 * 24 * 60 * 60 * 1000),
  },
  {
    id: "mock-project-10",
    title: "日本人の配偶者等ビザの申請",
    name: "Suthipong Somchai",
    nameEnglish: "Somchai Suthipong",
    nationality: "タイ",
    visaType: "日本人の配偶者等",
    currentVisaType: "短期滞在",
    expiryDate: expired3DaysAgo, // 期限切れ
    status: convertStatus("審査中"),
    createdAt: new Date(now.getTime() - 20 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000),
  },
  {
    id: "mock-project-11",
    title: "永住者の配偶者等ビザの申請",
    name: "Widodo Budi",
    nameEnglish: "Budi Widodo",
    nationality: "インドネシア",
    visaType: "永住者の配偶者等",
    currentVisaType: "定住者",
    expiryDate: nextMonth,
    status: convertStatus("完了"),
    createdAt: new Date(now.getTime() - 45 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000),
  },
  {
    id: "mock-project-12",
    title: "特定活動ビザの申請",
    name: "Chen Wei",
    nameEnglish: "Wei Chen",
    nationality: "中国",
    visaType: "特定活動",
    currentVisaType: "技術・人文知識・国際業務",
    expiryDate: expired1, // 期限切れ
    status: convertStatus("準備中"),
    createdAt: new Date(now.getTime() - 15 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(now.getTime() - 4 * 24 * 60 * 60 * 1000),
  },
  {
    id: "mock-project-13",
    title: "技術・人文知識・国際業務の申請",
    name: "Kim Soo-jin",
    nameEnglish: "Soo-jin Kim",
    nationality: "韓国",
    visaType: "技術・人文知識・国際業務",
    currentVisaType: "留学",
    expiryDate: nextWeek, // 期限切れ間近
    status: convertStatus("審査中"),
    createdAt: new Date(now.getTime() - 18 * 24 * 60 * 60 * 1000),
    updatedAt: yesterday,
  },
  {
    id: "mock-project-14",
    title: "経営・管理ビザの申請",
    name: "Williams David",
    nameEnglish: "David Williams",
    nationality: "アメリカ",
    visaType: "経営・管理",
    currentVisaType: "技術・人文知識・国際業務",
    expiryDate: nextMonth,
    status: convertStatus("完了"),
    createdAt: new Date(now.getTime() - 60 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(now.getTime() - 10 * 24 * 60 * 60 * 1000),
  },
  {
    id: "mock-project-15",
    title: "定住者ビザの申請",
    name: "Tran Thi B",
    nameEnglish: "Thi B Tran",
    nationality: "ベトナム",
    visaType: "定住者",
    currentVisaType: "技能実習",
    expiryDate: null,
    status: convertStatus("完了"),
    createdAt: new Date(now.getTime() - 50 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000),
  },
];

/**
 * 書類のモックデータ（プロジェクトIDごとに分類）
 */
export const mockDocuments: ProjectDocument[] = [
  // mock-project-1 の書類
  {
    id: "mock-doc-1-1",
    projectId: "mock-project-1",
    name: "パスポート写し.pdf",
    category: "本人書類",
    status: "uploaded",
    isRequiredOriginal: true,
    fileUrl: "https://example.com/documents/passport.pdf",
    storagePath: "projects/mock-project-1/documents/passport.pdf",
    createdAt: new Date(now.getTime() - 6 * 24 * 60 * 60 * 1000),
  },
  {
    id: "mock-doc-1-2",
    projectId: "mock-project-1",
    name: "履歴書.pdf",
    category: "本人書類",
    status: "verified",
    fileUrl: "https://example.com/documents/resume.pdf",
    storagePath: "projects/mock-project-1/documents/resume.pdf",
    createdAt: new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000),
  },
  {
    id: "mock-doc-1-3",
    projectId: "mock-project-1",
    name: "在留カード写し.pdf",
    category: "本人書類",
    status: "pending",
    isRequiredOriginal: true,
    createdAt: new Date(now.getTime() - 4 * 24 * 60 * 60 * 1000),
  },
  // mock-project-2 の書類
  {
    id: "mock-doc-2-1",
    projectId: "mock-project-2",
    name: "事業計画書.pdf",
    category: "作成書類",
    status: "uploaded",
    fileUrl: "https://example.com/documents/business_plan.pdf",
    storagePath: "projects/mock-project-2/documents/business_plan.pdf",
    createdAt: new Date(now.getTime() - 4 * 24 * 60 * 60 * 1000),
  },
  {
    id: "mock-doc-2-2",
    projectId: "mock-project-2",
    name: "登記簿謄本.pdf",
    category: "勤務先書類",
    status: "verified",
    fileUrl: "https://example.com/documents/registry.pdf",
    storagePath: "projects/mock-project-2/documents/registry.pdf",
    createdAt: new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000),
  },
  // mock-project-3 の書類
  {
    id: "mock-doc-3-1",
    projectId: "mock-project-3",
    name: "納税証明書.pdf",
    category: "本人書類",
    status: "uploaded",
    fileUrl: "https://example.com/documents/tax_certificate.pdf",
    storagePath: "projects/mock-project-3/documents/tax_certificate.pdf",
    createdAt: new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000),
  },
  {
    id: "mock-doc-3-2",
    projectId: "mock-project-3",
    name: "住民票.pdf",
    category: "本人書類",
    status: "pending",
    isRequiredOriginal: true,
    createdAt: new Date(now.getTime() - 1 * 24 * 60 * 60 * 1000),
  },
  // mock-project-4 の書類
  {
    id: "mock-doc-4-1",
    projectId: "mock-project-4",
    name: "入学許可書.pdf",
    category: "本人書類",
    status: "verified",
    fileUrl: "https://example.com/documents/admission.pdf",
    storagePath: "projects/mock-project-4/documents/admission.pdf",
    createdAt: new Date(now.getTime() - 9 * 24 * 60 * 60 * 1000),
  },
  {
    id: "mock-doc-4-2",
    projectId: "mock-project-4",
    name: "学費納入証明書.pdf",
    category: "本人書類",
    status: "uploaded",
    fileUrl: "https://example.com/documents/tuition.pdf",
    storagePath: "projects/mock-project-4/documents/tuition.pdf",
    createdAt: new Date(now.getTime() - 8 * 24 * 60 * 60 * 1000),
  },
  // mock-project-5 の書類
  {
    id: "mock-doc-5-1",
    projectId: "mock-project-5",
    name: "ポイント計算表.pdf",
    category: "作成書類",
    status: "uploaded",
    fileUrl: "https://example.com/documents/points.pdf",
    storagePath: "projects/mock-project-5/documents/points.pdf",
    createdAt: new Date(now.getTime() - 13 * 24 * 60 * 60 * 1000),
  },
  // mock-project-6 の書類
  {
    id: "mock-doc-6-1",
    projectId: "mock-project-6",
    name: "婚姻証明書.pdf",
    category: "本人書類",
    status: "verified",
    isRequiredOriginal: true,
    fileUrl: "https://example.com/documents/marriage.pdf",
    storagePath: "projects/mock-project-6/documents/marriage.pdf",
    createdAt: new Date(now.getTime() - 29 * 24 * 60 * 60 * 1000),
  },
  {
    id: "mock-doc-6-2",
    projectId: "mock-project-6",
    name: "出生証明書.pdf",
    category: "本人書類",
    status: "verified",
    isRequiredOriginal: true,
    fileUrl: "https://example.com/documents/birth.pdf",
    storagePath: "projects/mock-project-6/documents/birth.pdf",
    createdAt: new Date(now.getTime() - 28 * 24 * 60 * 60 * 1000),
  },
  // mock-project-7 の書類
  {
    id: "mock-doc-7-1",
    projectId: "mock-project-7",
    name: "技能実習計画書.pdf",
    category: "作成書類",
    status: "pending",
    createdAt: new Date(now.getTime() - 1 * 24 * 60 * 60 * 1000),
  },
  
  // 新しいプロジェクト（8-15）の書類を追加
  // mock-project-8 の書類（定住者）
  {
    id: "mock-doc-8-1",
    projectId: "mock-project-8",
    name: "パスポート写し",
    category: "personal",
    source: "applicant",
    assignedTo: "applicant",
    status: "collected",
    isRequiredOriginal: true,
    fileUrl: "https://example.com/documents/passport.pdf",
    storagePath: "projects/mock-project-8/documents/passport.pdf",
    createdAt: new Date(now.getTime() - 18 * 24 * 60 * 60 * 1000),
  },
  {
    id: "mock-doc-8-2",
    projectId: "mock-project-8",
    name: "在留カード写し",
    category: "personal",
    source: "applicant",
    assignedTo: "applicant",
    status: "collected",
    isRequiredOriginal: true,
    fileUrl: "https://example.com/documents/residence_card.pdf",
    storagePath: "projects/mock-project-8/documents/residence_card.pdf",
    createdAt: new Date(now.getTime() - 17 * 24 * 60 * 60 * 1000),
  },
  {
    id: "mock-doc-8-3",
    projectId: "mock-project-8",
    name: "住民票",
    category: "government",
    source: "government",
    assignedTo: "applicant",
    status: "collected",
    isRequiredOriginal: true,
    fileUrl: "https://example.com/documents/resident_card.pdf",
    storagePath: "projects/mock-project-8/documents/resident_card.pdf",
    createdAt: new Date(now.getTime() - 16 * 24 * 60 * 60 * 1000),
  },
  {
    id: "mock-doc-8-4",
    projectId: "mock-project-8",
    name: "納税証明書",
    category: "government",
    source: "government",
    assignedTo: "applicant",
    status: "verified",
    isRequiredOriginal: false,
    fileUrl: "https://example.com/documents/tax_certificate.pdf",
    storagePath: "projects/mock-project-8/documents/tax_certificate.pdf",
    createdAt: new Date(now.getTime() - 15 * 24 * 60 * 60 * 1000),
  },
  {
    id: "mock-doc-8-5",
    projectId: "mock-project-8",
    name: "申請理由書",
    category: "office",
    source: "office",
    assignedTo: "office",
    status: "in_progress",
    isRequiredOriginal: false,
    createdAt: new Date(now.getTime() - 14 * 24 * 60 * 60 * 1000),
  },
  {
    id: "mock-doc-8-6",
    projectId: "mock-project-8",
    name: "申請書類",
    category: "office",
    source: "office",
    assignedTo: "office",
    status: "waiting",
    isRequiredOriginal: false,
    canCreateAfter: ["mock-doc-8-1", "mock-doc-8-2", "mock-doc-8-3"],
    createdAt: new Date(now.getTime() - 13 * 24 * 60 * 60 * 1000),
  },

  // mock-project-9 の書類（技術・人文知識・国際業務）
  {
    id: "mock-doc-9-1",
    projectId: "mock-project-9",
    name: "パスポート写し",
    category: "personal",
    source: "applicant",
    assignedTo: "applicant",
    status: "collected",
    isRequiredOriginal: true,
    fileUrl: "https://example.com/documents/passport.pdf",
    storagePath: "projects/mock-project-9/documents/passport.pdf",
    createdAt: new Date(now.getTime() - 38 * 24 * 60 * 60 * 1000),
  },
  {
    id: "mock-doc-9-2",
    projectId: "mock-project-9",
    name: "在留カード写し",
    category: "personal",
    source: "applicant",
    assignedTo: "applicant",
    status: "collected",
    isRequiredOriginal: true,
    fileUrl: "https://example.com/documents/residence_card.pdf",
    storagePath: "projects/mock-project-9/documents/residence_card.pdf",
    createdAt: new Date(now.getTime() - 37 * 24 * 60 * 60 * 1000),
  },
  {
    id: "mock-doc-9-3",
    projectId: "mock-project-9",
    name: "履歴書",
    category: "personal",
    source: "applicant",
    assignedTo: "applicant",
    status: "collected",
    isRequiredOriginal: false,
    fileUrl: "https://example.com/documents/resume.pdf",
    storagePath: "projects/mock-project-9/documents/resume.pdf",
    createdAt: new Date(now.getTime() - 36 * 24 * 60 * 60 * 1000),
  },
  {
    id: "mock-doc-9-4",
    projectId: "mock-project-9",
    name: "卒業証明書",
    category: "personal",
    source: "applicant",
    assignedTo: "applicant",
    status: "collected",
    isRequiredOriginal: true,
    fileUrl: "https://example.com/documents/graduation_certificate.pdf",
    storagePath: "projects/mock-project-9/documents/graduation_certificate.pdf",
    createdAt: new Date(now.getTime() - 35 * 24 * 60 * 60 * 1000),
  },
  {
    id: "mock-doc-9-5",
    projectId: "mock-project-9",
    name: "雇用契約書",
    category: "employer",
    source: "employer",
    assignedTo: "applicant",
    status: "waiting",
    isRequiredOriginal: false,
    createdAt: new Date(now.getTime() - 34 * 24 * 60 * 60 * 1000),
  },
  {
    id: "mock-doc-9-6",
    projectId: "mock-project-9",
    name: "給与明細",
    category: "employer",
    source: "employer",
    assignedTo: "applicant",
    status: "not_started",
    isRequiredOriginal: false,
    createdAt: new Date(now.getTime() - 33 * 24 * 60 * 60 * 1000),
  },
  {
    id: "mock-doc-9-7",
    projectId: "mock-project-9",
    name: "在職証明書",
    category: "employer",
    source: "employer",
    assignedTo: "applicant",
    status: "not_started",
    isRequiredOriginal: false,
    createdAt: new Date(now.getTime() - 32 * 24 * 60 * 60 * 1000),
  },
  {
    id: "mock-doc-9-8",
    projectId: "mock-project-9",
    name: "申請書類",
    category: "office",
    source: "office",
    assignedTo: "office",
    status: "waiting",
    isRequiredOriginal: false,
    canCreateAfter: ["mock-doc-9-1", "mock-doc-9-2", "mock-doc-9-3", "mock-doc-9-4"],
    createdAt: new Date(now.getTime() - 31 * 24 * 60 * 60 * 1000),
  },

  // mock-project-10 の書類（日本人の配偶者等）
  {
    id: "mock-doc-10-1",
    projectId: "mock-project-10",
    name: "パスポート写し",
    category: "personal",
    source: "applicant",
    assignedTo: "applicant",
    status: "collected",
    isRequiredOriginal: true,
    fileUrl: "https://example.com/documents/passport.pdf",
    storagePath: "projects/mock-project-10/documents/passport.pdf",
    createdAt: new Date(now.getTime() - 13 * 24 * 60 * 60 * 1000),
  },
  {
    id: "mock-doc-10-2",
    projectId: "mock-project-10",
    name: "在留カード写し",
    category: "personal",
    source: "applicant",
    assignedTo: "applicant",
    status: "collected",
    isRequiredOriginal: true,
    fileUrl: "https://example.com/documents/residence_card.pdf",
    storagePath: "projects/mock-project-10/documents/residence_card.pdf",
    createdAt: new Date(now.getTime() - 12 * 24 * 60 * 60 * 1000),
  },
  {
    id: "mock-doc-10-3",
    projectId: "mock-project-10",
    name: "住民票",
    category: "government",
    source: "government",
    assignedTo: "applicant",
    status: "collected",
    isRequiredOriginal: true,
    fileUrl: "https://example.com/documents/resident_card.pdf",
    storagePath: "projects/mock-project-10/documents/resident_card.pdf",
    createdAt: new Date(now.getTime() - 11 * 24 * 60 * 60 * 1000),
  },
  {
    id: "mock-doc-10-4",
    projectId: "mock-project-10",
    name: "婚姻届受理証明書",
    category: "government",
    source: "government",
    assignedTo: "applicant",
    status: "collected",
    isRequiredOriginal: true,
    fileUrl: "https://example.com/documents/marriage_certificate.pdf",
    storagePath: "projects/mock-project-10/documents/marriage_certificate.pdf",
    createdAt: new Date(now.getTime() - 10 * 24 * 60 * 60 * 1000),
  },
  {
    id: "mock-doc-10-5",
    projectId: "mock-project-10",
    name: "配偶者の在留カード写し",
    category: "personal",
    source: "applicant",
    assignedTo: "applicant",
    status: "collected",
    isRequiredOriginal: true,
    fileUrl: "https://example.com/documents/spouse_residence_card.pdf",
    storagePath: "projects/mock-project-10/documents/spouse_residence_card.pdf",
    createdAt: new Date(now.getTime() - 9 * 24 * 60 * 60 * 1000),
  },
  {
    id: "mock-doc-10-6",
    projectId: "mock-project-10",
    name: "申請理由書",
    category: "office",
    source: "office",
    assignedTo: "office",
    status: "in_progress",
    isRequiredOriginal: false,
    createdAt: new Date(now.getTime() - 8 * 24 * 60 * 60 * 1000),
  },
  {
    id: "mock-doc-10-7",
    projectId: "mock-project-10",
    name: "申請書類",
    category: "office",
    source: "office",
    assignedTo: "office",
    status: "waiting",
    isRequiredOriginal: false,
    canCreateAfter: ["mock-doc-10-1", "mock-doc-10-2", "mock-doc-10-3", "mock-doc-10-4"],
    createdAt: new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000),
  },

  // mock-project-11 の書類（永住者の配偶者等）
  {
    id: "mock-doc-11-1",
    projectId: "mock-project-11",
    name: "パスポート写し",
    category: "personal",
    source: "applicant",
    assignedTo: "applicant",
    status: "collected",
    isRequiredOriginal: true,
    fileUrl: "https://example.com/documents/passport.pdf",
    storagePath: "projects/mock-project-11/documents/passport.pdf",
    createdAt: new Date(now.getTime() - 23 * 24 * 60 * 60 * 1000),
  },
  {
    id: "mock-doc-11-2",
    projectId: "mock-project-11",
    name: "在留カード写し",
    category: "personal",
    source: "applicant",
    assignedTo: "applicant",
    status: "collected",
    isRequiredOriginal: true,
    fileUrl: "https://example.com/documents/residence_card.pdf",
    storagePath: "projects/mock-project-11/documents/residence_card.pdf",
    createdAt: new Date(now.getTime() - 22 * 24 * 60 * 60 * 1000),
  },
  {
    id: "mock-doc-11-3",
    projectId: "mock-project-11",
    name: "住民票",
    category: "government",
    source: "government",
    assignedTo: "applicant",
    status: "collected",
    isRequiredOriginal: true,
    fileUrl: "https://example.com/documents/resident_card.pdf",
    storagePath: "projects/mock-project-11/documents/resident_card.pdf",
    createdAt: new Date(now.getTime() - 21 * 24 * 60 * 60 * 1000),
  },
  {
    id: "mock-doc-11-4",
    projectId: "mock-project-11",
    name: "納税証明書",
    category: "government",
    source: "government",
    assignedTo: "applicant",
    status: "verified",
    isRequiredOriginal: false,
    era: "reiwa",
    eraYear: 6,
    year: 2024,
    fileUrl: "https://example.com/documents/tax_certificate_r6.pdf",
    storagePath: "projects/mock-project-11/documents/tax_certificate_r6.pdf",
    createdAt: new Date(now.getTime() - 20 * 24 * 60 * 60 * 1000),
  },
  {
    id: "mock-doc-11-5",
    projectId: "mock-project-11",
    name: "課税証明書",
    category: "government",
    source: "government",
    assignedTo: "applicant",
    status: "collected",
    isRequiredOriginal: false,
    era: "reiwa",
    eraYear: 6,
    year: 2024,
    fileUrl: "https://example.com/documents/taxation_certificate_r6.pdf",
    storagePath: "projects/mock-project-11/documents/taxation_certificate_r6.pdf",
    createdAt: new Date(now.getTime() - 19 * 24 * 60 * 60 * 1000),
  },
  {
    id: "mock-doc-11-6",
    projectId: "mock-project-11",
    name: "申請理由書",
    category: "office",
    source: "office",
    assignedTo: "office",
    status: "in_progress",
    isRequiredOriginal: false,
    createdAt: new Date(now.getTime() - 18 * 24 * 60 * 60 * 1000),
  },
  {
    id: "mock-doc-11-7",
    projectId: "mock-project-11",
    name: "申請書類",
    category: "office",
    source: "office",
    assignedTo: "office",
    status: "waiting",
    isRequiredOriginal: false,
    canCreateAfter: ["mock-doc-11-1", "mock-doc-11-2", "mock-doc-11-3"],
    createdAt: new Date(now.getTime() - 17 * 24 * 60 * 60 * 1000),
  },

  // mock-project-12 の書類（特定活動）
  {
    id: "mock-doc-12-1",
    projectId: "mock-project-12",
    name: "パスポート写し",
    category: "personal",
    source: "applicant",
    assignedTo: "applicant",
    status: "completed",
    isRequiredOriginal: true,
    fileUrl: "https://example.com/documents/passport.pdf",
    storagePath: "projects/mock-project-12/documents/passport.pdf",
    createdAt: new Date(now.getTime() - 58 * 24 * 60 * 60 * 1000),
  },
  {
    id: "mock-doc-12-2",
    projectId: "mock-project-12",
    name: "在留カード写し",
    category: "personal",
    source: "applicant",
    assignedTo: "applicant",
    status: "completed",
    isRequiredOriginal: true,
    fileUrl: "https://example.com/documents/residence_card.pdf",
    storagePath: "projects/mock-project-12/documents/residence_card.pdf",
    createdAt: new Date(now.getTime() - 57 * 24 * 60 * 60 * 1000),
  },
  {
    id: "mock-doc-12-3",
    projectId: "mock-project-12",
    name: "申請書類",
    category: "office",
    source: "office",
    assignedTo: "office",
    status: "completed",
    isRequiredOriginal: false,
    fileUrl: "https://example.com/documents/application.pdf",
    storagePath: "projects/mock-project-12/documents/application.pdf",
    createdAt: new Date(now.getTime() - 56 * 24 * 60 * 60 * 1000),
  },
  {
    id: "mock-doc-12-4",
    projectId: "mock-project-12",
    name: "申請理由書",
    category: "office",
    source: "office",
    assignedTo: "office",
    status: "completed",
    isRequiredOriginal: false,
    fileUrl: "https://example.com/documents/reason_statement.pdf",
    storagePath: "projects/mock-project-12/documents/reason_statement.pdf",
    createdAt: new Date(now.getTime() - 55 * 24 * 60 * 60 * 1000),
  },
  {
    id: "mock-doc-12-5",
    projectId: "mock-project-12",
    name: "住民票",
    category: "government",
    source: "government",
    assignedTo: "applicant",
    status: "completed",
    isRequiredOriginal: true,
    fileUrl: "https://example.com/documents/resident_card.pdf",
    storagePath: "projects/mock-project-12/documents/resident_card.pdf",
    createdAt: new Date(now.getTime() - 54 * 24 * 60 * 60 * 1000),
  },

  // mock-project-13 の書類（経営・管理）
  {
    id: "mock-doc-13-1",
    projectId: "mock-project-13",
    name: "パスポート写し",
    category: "personal",
    source: "applicant",
    assignedTo: "applicant",
    status: "collected",
    isRequiredOriginal: true,
    fileUrl: "https://example.com/documents/passport.pdf",
    storagePath: "projects/mock-project-13/documents/passport.pdf",
    createdAt: new Date(now.getTime() - 6 * 24 * 60 * 60 * 1000),
  },
  {
    id: "mock-doc-13-2",
    projectId: "mock-project-13",
    name: "在留カード写し",
    category: "personal",
    source: "applicant",
    assignedTo: "applicant",
    status: "collected",
    isRequiredOriginal: true,
    fileUrl: "https://example.com/documents/residence_card.pdf",
    storagePath: "projects/mock-project-13/documents/residence_card.pdf",
    createdAt: new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000),
  },
  {
    id: "mock-doc-13-3",
    projectId: "mock-project-13",
    name: "事業計画書",
    category: "office",
    source: "office",
    assignedTo: "office",
    status: "in_progress",
    isRequiredOriginal: false,
    createdAt: new Date(now.getTime() - 4 * 24 * 60 * 60 * 1000),
  },
  {
    id: "mock-doc-13-4",
    projectId: "mock-project-13",
    name: "登記簿謄本",
    category: "employer",
    source: "employer",
    assignedTo: "applicant",
    status: "waiting",
    isRequiredOriginal: false,
    createdAt: new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000),
  },
  {
    id: "mock-doc-13-5",
    projectId: "mock-project-13",
    name: "定款",
    category: "employer",
    source: "employer",
    assignedTo: "applicant",
    status: "not_started",
    isRequiredOriginal: false,
    createdAt: new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000),
  },
  {
    id: "mock-doc-13-6",
    projectId: "mock-project-13",
    name: "申請書類",
    category: "office",
    source: "office",
    assignedTo: "office",
    status: "waiting",
    isRequiredOriginal: false,
    canCreateAfter: ["mock-doc-13-1", "mock-doc-13-2", "mock-doc-13-3"],
    createdAt: new Date(now.getTime() - 1 * 24 * 60 * 60 * 1000),
  },

  // mock-project-14 の書類（高度専門職）
  {
    id: "mock-doc-14-1",
    projectId: "mock-project-14",
    name: "パスポート写し",
    category: "personal",
    source: "applicant",
    assignedTo: "applicant",
    status: "collected",
    isRequiredOriginal: true,
    fileUrl: "https://example.com/documents/passport.pdf",
    storagePath: "projects/mock-project-14/documents/passport.pdf",
    createdAt: new Date(now.getTime() - 10 * 24 * 60 * 60 * 1000),
  },
  {
    id: "mock-doc-14-2",
    projectId: "mock-project-14",
    name: "在留カード写し",
    category: "personal",
    source: "applicant",
    assignedTo: "applicant",
    status: "collected",
    isRequiredOriginal: true,
    fileUrl: "https://example.com/documents/residence_card.pdf",
    storagePath: "projects/mock-project-14/documents/residence_card.pdf",
    createdAt: new Date(now.getTime() - 9 * 24 * 60 * 60 * 1000),
  },
  {
    id: "mock-doc-14-3",
    projectId: "mock-project-14",
    name: "履歴書",
    category: "personal",
    source: "applicant",
    assignedTo: "applicant",
    status: "collected",
    isRequiredOriginal: false,
    fileUrl: "https://example.com/documents/resume.pdf",
    storagePath: "projects/mock-project-14/documents/resume.pdf",
    createdAt: new Date(now.getTime() - 8 * 24 * 60 * 60 * 1000),
  },
  {
    id: "mock-doc-14-4",
    projectId: "mock-project-14",
    name: "卒業証明書",
    category: "personal",
    source: "applicant",
    assignedTo: "applicant",
    status: "collected",
    isRequiredOriginal: true,
    fileUrl: "https://example.com/documents/graduation_certificate.pdf",
    storagePath: "projects/mock-project-14/documents/graduation_certificate.pdf",
    createdAt: new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000),
  },
  {
    id: "mock-doc-14-5",
    projectId: "mock-project-14",
    name: "雇用契約書",
    category: "employer",
    source: "employer",
    assignedTo: "applicant",
    status: "collected",
    isRequiredOriginal: false,
    fileUrl: "https://example.com/documents/employment_contract.pdf",
    storagePath: "projects/mock-project-14/documents/employment_contract.pdf",
    createdAt: new Date(now.getTime() - 6 * 24 * 60 * 60 * 1000),
  },
  {
    id: "mock-doc-14-6",
    projectId: "mock-project-14",
    name: "給与明細",
    category: "employer",
    source: "employer",
    assignedTo: "applicant",
    status: "collected",
    isRequiredOriginal: false,
    fileUrl: "https://example.com/documents/payroll.pdf",
    storagePath: "projects/mock-project-14/documents/payroll.pdf",
    createdAt: new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000),
  },
  {
    id: "mock-doc-14-7",
    projectId: "mock-project-14",
    name: "在職証明書",
    category: "employer",
    source: "employer",
    assignedTo: "applicant",
    status: "verified",
    isRequiredOriginal: false,
    fileUrl: "https://example.com/documents/employment_certificate.pdf",
    storagePath: "projects/mock-project-14/documents/employment_certificate.pdf",
    createdAt: new Date(now.getTime() - 4 * 24 * 60 * 60 * 1000),
  },
  {
    id: "mock-doc-14-8",
    projectId: "mock-project-14",
    name: "申請書類",
    category: "office",
    source: "office",
    assignedTo: "office",
    status: "in_progress",
    isRequiredOriginal: false,
    createdAt: new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000),
  },
  {
    id: "mock-doc-14-9",
    projectId: "mock-project-14",
    name: "申請理由書",
    category: "office",
    source: "office",
    assignedTo: "office",
    status: "waiting",
    isRequiredOriginal: false,
    canCreateAfter: ["mock-doc-14-1", "mock-doc-14-2", "mock-doc-14-3"],
    createdAt: new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000),
  },

  // mock-project-15 の書類（技能実習）
  {
    id: "mock-doc-15-1",
    projectId: "mock-project-15",
    name: "パスポート写し",
    category: "personal",
    source: "applicant",
    assignedTo: "applicant",
    status: "completed",
    isRequiredOriginal: true,
    fileUrl: "https://example.com/documents/passport.pdf",
    storagePath: "projects/mock-project-15/documents/passport.pdf",
    createdAt: new Date(now.getTime() - 43 * 24 * 60 * 60 * 1000),
  },
  {
    id: "mock-doc-15-2",
    projectId: "mock-project-15",
    name: "在留カード写し",
    category: "personal",
    source: "applicant",
    assignedTo: "applicant",
    status: "completed",
    isRequiredOriginal: true,
    fileUrl: "https://example.com/documents/residence_card.pdf",
    storagePath: "projects/mock-project-15/documents/residence_card.pdf",
    createdAt: new Date(now.getTime() - 42 * 24 * 60 * 60 * 1000),
  },
  {
    id: "mock-doc-15-3",
    projectId: "mock-project-15",
    name: "技能実習計画書",
    category: "employer",
    source: "employer",
    assignedTo: "applicant",
    status: "completed",
    isRequiredOriginal: false,
    fileUrl: "https://example.com/documents/training_plan.pdf",
    storagePath: "projects/mock-project-15/documents/training_plan.pdf",
    createdAt: new Date(now.getTime() - 41 * 24 * 60 * 60 * 1000),
  },
  {
    id: "mock-doc-15-4",
    projectId: "mock-project-15",
    name: "雇用契約書",
    category: "employer",
    source: "employer",
    assignedTo: "applicant",
    status: "completed",
    isRequiredOriginal: false,
    fileUrl: "https://example.com/documents/employment_contract.pdf",
    storagePath: "projects/mock-project-15/documents/employment_contract.pdf",
    createdAt: new Date(now.getTime() - 40 * 24 * 60 * 60 * 1000),
  },
  {
    id: "mock-doc-15-5",
    projectId: "mock-project-15",
    name: "申請書類",
    category: "office",
    source: "office",
    assignedTo: "office",
    status: "completed",
    isRequiredOriginal: false,
    fileUrl: "https://example.com/documents/application.pdf",
    storagePath: "projects/mock-project-15/documents/application.pdf",
    createdAt: new Date(now.getTime() - 39 * 24 * 60 * 60 * 1000),
  },
];
