import { ProjectDocument } from "@/types";

/**
 * 書類テンプレートの型定義
 * ProjectDocumentから id, projectId, createdAt, updatedAt, fileUrl, storagePath を除外
 */
export interface DocumentTemplate {
  visaType: string;
  documents: Omit<
    ProjectDocument,
    "id" | "projectId" | "createdAt" | "updatedAt" | "fileUrl" | "storagePath"
 >[];
}

/**
 * 案件種別ごとの書類テンプレート
 */
export const documentTemplates: DocumentTemplate[] = [
  {
    visaType: "技術・人文知識・国際業務",
    documents: [
      {
        name: "在留資格変更許可申請書",
        description: "1通",
        category: "office",
        source: "office",
        assignedTo: "office",
        status: "not_started",
        isRequiredOriginal: false,
      },
      {
        name: "パスポートの写し",
        description: "顔写真のあるページ",
        category: "personal",
        source: "applicant",
        assignedTo: "applicant",
        status: "not_started",
        isRequiredOriginal: true,
      },
      {
        name: "在留カードの写し",
        description: "表裏両面",
        category: "personal",
        source: "applicant",
        assignedTo: "applicant",
        status: "not_started",
        isRequiredOriginal: true,
      },
      {
        name: "写真",
        description: "縦4cm×横3cm、3ヶ月以内に撮影",
        category: "personal",
        source: "applicant",
        assignedTo: "applicant",
        status: "not_started",
        isRequiredOriginal: false,
      },
      {
        name: "在留資格変更許可申請書の添付書類",
        description: "申請理由書",
        category: "office",
        source: "office",
        assignedTo: "office",
        status: "not_started",
        isRequiredOriginal: false,
      },
      {
        name: "履歴書",
        description: "職歴を詳しく記載",
        category: "personal",
        source: "applicant",
        assignedTo: "applicant",
        status: "not_started",
        isRequiredOriginal: false,
      },
      {
        name: "卒業証明書",
        description: "最終学歴のもの",
        category: "personal",
        source: "applicant",
        assignedTo: "applicant",
        status: "not_started",
        isRequiredOriginal: true,
      },
      {
        name: "成績証明書",
        description: "最終学歴のもの",
        category: "personal",
        source: "applicant",
        assignedTo: "applicant",
        status: "not_started",
        isRequiredOriginal: true,
      },
      {
        name: "雇用契約書の写し",
        description: "または採用内定通知書",
        category: "employer",
        source: "employer",
        assignedTo: "applicant",
        status: "not_started",
        isRequiredOriginal: false,
      },
      {
        name: "給与明細書",
        description: "直近3ヶ月分",
        category: "employer",
        source: "employer",
        assignedTo: "applicant",
        status: "not_started",
        isRequiredOriginal: false,
      },
      {
        name: "源泉徴収票",
        description: "直近1年分",
        category: "employer",
        source: "employer",
        assignedTo: "applicant",
        status: "not_started",
        isRequiredOriginal: true,
      },
      {
        name: "会社の登記事項証明書",
        description: "3ヶ月以内発行のもの",
        category: "employer",
        source: "employer",
        assignedTo: "applicant",
        status: "not_started",
        isRequiredOriginal: true,
      },
      {
        name: "会社案内",
        description: "事業内容が分かるもの",
        category: "employer",
        source: "employer",
        assignedTo: "applicant",
        status: "not_started",
        isRequiredOriginal: false,
      },
      {
        name: "従業員数・外国人従業員数の証明書",
        description: "会社が作成",
        category: "employer",
        source: "employer",
        assignedTo: "applicant",
        status: "not_started",
        isRequiredOriginal: false,
      },
      {
        name: "事業内容説明書",
        description: "会社が作成",
        category: "employer",
        source: "employer",
        assignedTo: "applicant",
        status: "not_started",
        isRequiredOriginal: false,
      },
      {
        name: "雇用理由書",
        description: "会社が作成",
        category: "employer",
        source: "employer",
        assignedTo: "applicant",
        status: "not_started",
        isRequiredOriginal: false,
      },
      {
        name: "申請人の職務内容説明書",
        description: "会社が作成",
        category: "employer",
        source: "employer",
        assignedTo: "applicant",
        status: "not_started",
        isRequiredOriginal: false,
      },
      {
        name: "申請人の経歴書",
        description: "職務経歴を詳しく記載",
        category: "personal",
        source: "applicant",
        assignedTo: "applicant",
        status: "not_started",
        isRequiredOriginal: false,
      },
      {
        name: "住民票の写し",
        description: "3ヶ月以内発行のもの",
        category: "government",
        source: "applicant",
        assignedTo: "applicant",
        status: "not_started",
        isRequiredOriginal: true,
      },
      {
        name: "納税証明書",
        description: "直近1年分",
        category: "government",
        source: "government",
        assignedTo: "applicant",
        status: "not_started",
        isRequiredOriginal: true,
      },
      {
        name: "健康保険証の写し",
        description: "表裏両面",
        category: "personal",
        source: "applicant",
        assignedTo: "applicant",
        status: "not_started",
        isRequiredOriginal: false,
      },
      {
        name: "年金記録の確認応答書",
        description: "直近1年分",
        category: "government",
        source: "government",
        assignedTo: "applicant",
        status: "not_started",
        isRequiredOriginal: true,
      },
      {
        name: "申請人の職務に関する証明書",
        description: "会社が作成",
        category: "employer",
        source: "employer",
        assignedTo: "applicant",
        status: "not_started",
        isRequiredOriginal: false,
      },
      {
        name: "申請人の学歴に関する証明書",
        description: "最終学歴のもの",
        category: "personal",
        source: "applicant",
        assignedTo: "applicant",
        status: "not_started",
        isRequiredOriginal: true,
      },
      {
        name: "申請人の資格に関する証明書",
        description: "関連資格がある場合",
        category: "personal",
        source: "applicant",
        assignedTo: "applicant",
        status: "not_started",
        isRequiredOriginal: true,
      },
      {
        name: "申請人の語学能力に関する証明書",
        description: "TOEIC、TOEFL等",
        category: "personal",
        source: "applicant",
        assignedTo: "applicant",
        status: "not_started",
        isRequiredOriginal: false,
      },
      {
        name: "申請人の職務に関する実務経験証明書",
        description: "会社が作成",
        category: "employer",
        source: "employer",
        assignedTo: "applicant",
        status: "not_started",
        isRequiredOriginal: false,
      },
      {
        name: "申請人の職務に関する専門性証明書",
        description: "会社が作成",
        category: "employer",
        source: "employer",
        assignedTo: "applicant",
        status: "not_started",
        isRequiredOriginal: false,
      },
      {
        name: "申請人の職務に関する報酬証明書",
        description: "会社が作成",
        category: "employer",
        source: "employer",
        assignedTo: "applicant",
        status: "not_started",
        isRequiredOriginal: false,
      },
    ],
  },
  {
    visaType: "永住許可",
    documents: [
      {
        name: "永住許可申請書",
        description: "1通",
        category: "office",
        source: "office",
        assignedTo: "office",
        status: "not_started",
        isRequiredOriginal: false,
      },
      {
        name: "写真",
        description: "縦4cm×横3cm、3ヶ月以内に撮影",
        category: "personal",
        source: "applicant",
        assignedTo: "applicant",
        status: "not_started",
        isRequiredOriginal: false,
      },
      {
        name: "パスポートの写し",
        description: "顔写真のあるページ",
        category: "personal",
        source: "applicant",
        assignedTo: "applicant",
        status: "not_started",
        isRequiredOriginal: true,
      },
      {
        name: "在留カードの写し",
        description: "表裏両面",
        category: "personal",
        source: "applicant",
        assignedTo: "applicant",
        status: "not_started",
        isRequiredOriginal: true,
      },
      {
        name: "住民票の写し",
        description: "3ヶ月以内発行のもの",
        category: "government",
        source: "applicant",
        assignedTo: "applicant",
        status: "not_started",
        isRequiredOriginal: true,
      },
      {
        name: "納税証明書",
        description: "直近5年分",
        category: "government",
        source: "government",
        assignedTo: "applicant",
        status: "not_started",
        isRequiredOriginal: true,
      },
      {
        name: "課税証明書",
        description: "直近5年分",
        category: "government",
        source: "government",
        assignedTo: "applicant",
        status: "not_started",
        isRequiredOriginal: true,
      },
      {
        name: "年金記録の確認応答書",
        description: "直近5年分",
        category: "government",
        source: "government",
        assignedTo: "applicant",
        status: "not_started",
        isRequiredOriginal: true,
      },
      {
        name: "健康保険証の写し",
        description: "表裏両面",
        category: "personal",
        source: "applicant",
        assignedTo: "applicant",
        status: "not_started",
        isRequiredOriginal: false,
      },
      {
        name: "雇用契約書の写し",
        description: "または採用内定通知書",
        category: "employer",
        source: "employer",
        assignedTo: "applicant",
        status: "not_started",
        isRequiredOriginal: false,
      },
      {
        name: "給与明細書",
        description: "直近5年分",
        category: "employer",
        source: "employer",
        assignedTo: "applicant",
        status: "not_started",
        isRequiredOriginal: false,
      },
      {
        name: "源泉徴収票",
        description: "直近5年分",
        category: "employer",
        source: "employer",
        assignedTo: "applicant",
        status: "not_started",
        isRequiredOriginal: true,
      },
      {
        name: "会社の登記事項証明書",
        description: "3ヶ月以内発行のもの",
        category: "employer",
        source: "employer",
        assignedTo: "applicant",
        status: "not_started",
        isRequiredOriginal: true,
      },
      {
        name: "身元保証書",
        description: "身元保証人が作成",
        category: "other",
        source: "guarantor",
        assignedTo: "applicant",
        status: "not_started",
        isRequiredOriginal: false,
      },
      {
        name: "身元保証人の住民票の写し",
        description: "3ヶ月以内発行のもの",
        category: "other",
        source: "guarantor",
        assignedTo: "applicant",
        status: "not_started",
        isRequiredOriginal: true,
      },
      {
        name: "身元保証人の在職証明書",
        description: "または納税証明書",
        category: "other",
        source: "guarantor",
        assignedTo: "applicant",
        status: "not_started",
        isRequiredOriginal: true,
      },
      {
        name: "身元保証人の身分証明書の写し",
        description: "運転免許証等",
        category: "other",
        source: "guarantor",
        assignedTo: "applicant",
        status: "not_started",
        isRequiredOriginal: true,
      },
      {
        name: "申請人の履歴書",
        description: "職歴を詳しく記載",
        category: "personal",
        source: "applicant",
        assignedTo: "applicant",
        status: "not_started",
        isRequiredOriginal: false,
      },
      {
        name: "申請理由書",
        description: "永住許可を希望する理由",
        category: "office",
        source: "office",
        assignedTo: "office",
        status: "not_started",
        isRequiredOriginal: false,
      },
      {
        name: "素行が良好であることの証明書",
        description: "犯罪歴がないことの証明",
        category: "government",
        source: "government",
        assignedTo: "applicant",
        status: "not_started",
        isRequiredOriginal: true,
      },
      {
        name: "独立の生計を営むに足りる資産又は技能を有することの証明書",
        description: "資産証明書等",
        category: "personal",
        source: "applicant",
        assignedTo: "applicant",
        status: "not_started",
        isRequiredOriginal: true,
      },
      {
        name: "預金通帳の写し",
        description: "直近1年分",
        category: "personal",
        source: "applicant",
        assignedTo: "applicant",
        status: "not_started",
        isRequiredOriginal: false,
      },
      {
        name: "不動産登記簿謄本",
        description: "不動産を所有している場合",
        category: "personal",
        source: "applicant",
        assignedTo: "applicant",
        status: "not_started",
        isRequiredOriginal: true,
      },
      {
        name: "配偶者の在留カードの写し",
        description: "配偶者がいる場合",
        category: "personal",
        source: "applicant",
        assignedTo: "applicant",
        status: "not_started",
        isRequiredOriginal: true,
      },
      {
        name: "配偶者の住民票の写し",
        description: "配偶者がいる場合",
        category: "government",
        source: "applicant",
        assignedTo: "applicant",
        status: "not_started",
        isRequiredOriginal: true,
      },
      {
        name: "配偶者の納税証明書",
        description: "配偶者がいる場合、直近5年分",
        category: "government",
        source: "government",
        assignedTo: "applicant",
        status: "not_started",
        isRequiredOriginal: true,
      },
      {
        name: "子供の在留カードの写し",
        description: "子供がいる場合",
        category: "personal",
        source: "applicant",
        assignedTo: "applicant",
        status: "not_started",
        isRequiredOriginal: true,
      },
      {
        name: "子供の住民票の写し",
        description: "子供がいる場合",
        category: "government",
        source: "applicant",
        assignedTo: "applicant",
        status: "not_started",
        isRequiredOriginal: true,
      },
      {
        name: "健康診断書",
        description: "3ヶ月以内発行のもの",
        category: "personal",
        source: "applicant",
        assignedTo: "applicant",
        status: "not_started",
        isRequiredOriginal: true,
      },
      {
        name: "その他参考資料",
        description: "必要に応じて追加",
        category: "other",
        source: "other",
        assignedTo: "applicant",
        status: "not_started",
        isRequiredOriginal: false,
      },
    ],
  },
];

